### PR TITLE
Master loader paddr

### PR DESCRIPTION
**Pull request by max-ruttenberg**
* This should be merged with https://github.com/bespoke-silicon-group/bsg_manycore/pull/55

### CODE REVIEW

**Comment by drichmond** [comment]
is the format string issue separate?

**Comment by max-ruttenberg** [comment]
no, it's super related and the whole PR completely falls apart without it.

**Comment by drichmond** [comment]
Hokay

**Comment by drichmond** [comment]
v1.0.2 or v1.1.0?

**Comment by max-ruttenberg** [comment]
it's a patch

**Pull request merged**
