### PR TITLE
Add support for single-source multiple-tests

### PR DESCRIPTION
**Pull request by drichmond**
Added support in the compilation flow for compiling multiple tests using the same top-level .c file. 

(This PR depends on #284)

More documentation to follow

### CODE REVIEW

**Comment by max-ruttenberg** [comment]
ready for review?

**Comment by drichmond** [comment]
Almost.

**Comment by drichmond** [comment]
This one is ready too

**Comment by drichmond** [comment]
And yes, it passes in cosimulation

**Comment by max-ruttenberg** [comment]
Should be reviewed after https://github.com/bespoke-silicon-group/bsg_f1/pull/284

**Comment by max-ruttenberg** [comment]
@drichmond rebase?

**Comment by drichmond** [comment]
Fineeeeeee

**Comment by max-ruttenberg** [comment]
@drichmond this fails on F1 because of `cl_manycore_regression.h` needing to include `<stdint.h>`.
That's an easy to fix but the workaround is to include `<stdint.h>` in `test_unified_main.h` before `cl_manycore_regression.h`.

**Comment by drichmond** [comment]
Was this what you fixed yesterday? Or are there other issues?

**Comment by drichmond** [comment]
(Fixed above)

**Comment by max-ruttenberg** [comment]
The regression breaks on F1 for a couple of different reasons. 

* One of them is definitely related to using `uint32_t` before `<stdint.h>` has been included.
* After that there's some other missing header that's looks related to VCS.

I recommend taking a look on F1.

**Comment by drichmond** [comment]
This now runs (and passes) on F1

**Comment by max-ruttenberg** [comment]
@drichmond I've pushed a fix for the issues we were seeing. Given that it's my fix perhaps you should:

1. test on F1 (with clean bsg_f1 checkout)
2. test in cosim

**Comment by drichmond** [comment]
Yeah, will do

**Comment by drichmond** [comment]
Worked on F1 and in Cosim!

**Comment by drichmond** [comment]
@save-buffer - finished

**Pull request merged**
