### PR TITLE
Added Python Cosimulation support

### PR DESCRIPTION
**Pull request by drichmond**
This PR is only supported in VCS

This PR Adds support for writing cosimulation (and F1 tests) in Python, if a Manycore/Python API exists. 

It may be possible to run TVM tests in cosimulation with this PR. 

This PR depends on #284 and #287.

Documentation to follow

### CODE REVIEW

**Comment by max-ruttenberg** [comment]
ready for review?

**Comment by drichmond** [comment]
Almost.

**Comment by drichmond** [comment]
@max-ruttenberg This works too

**Comment by max-ruttenberg** [comment]
Should be reviewed after https://github.com/bespoke-silicon-group/bsg_f1/pull/287

**Comment by drichmond** [comment]
This works too

**Pull request merged**
