### PR TITLE
Added a new cuda regression test to initialize, load binary run and finish twice

### PR DESCRIPTION
**Pull request by bornaehsani**
This regression test is related to issue #300 but doesn't fix it yet.
On both F1 and cosim, the first kernel runs fine but the second kernel hangs.
**Should be merged in with bsg_manycore PR # 67.**

### CODE REVIEW

**Comment by drichmond** [comment]
Awesome! @soctar If we give you a .vcd file would you be able to put it into the undebugger?

**Comment by soctar** [comment]
Most definitely! If it's from VCS, it's helpful to have the VPD file as well, on the chance that you'd like to decompose structs.

**Comment by drichmond** [comment]
I can give you the vpd file instead!

**Comment by drichmond** [comment]
Or rather - @bornaehsani Can you give Neil the vpd file that is generated when you run this test?

**Comment by bornaehsani** [comment]
Sorry for the late response, and yes of course, however the file seems too large to send over, but Neil and I are planning to meet tomorrow so I can learn how to set up the debugger, perhaps we can go over it tomorrow together. Thanks!

**Comment by taylor-bsg** [comment]
Definitely suggest the smallest binary that manifests the problem, so you
are hunting for your needle in the small haystack possible. :-) VCD files
are very compressible, as well, but you can hand the file off on xor
diskbits.

**Pull request merged**
