### PR TITLE
fpu filelist change; load_id = 12

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by tommydcjung** [comment]
all test passed

**Comment by leonardxiang** [comment]
You might also need to change the build source file list at cl_manycore/build/encrypt.tcl

**Comment by drichmond** [comment]
@tommydcjung Can you make a separate PR for the load_id_width? Then we can use the file list changes for the FPU.

**Comment by drichmond** [comment]
Closed - out of date (I think?)

**Pull request closed without merging**
