### PR TITLE
switched to cpp headers

### PR DESCRIPTION
**Pull request by save-buffer**
Switched to conditionally include the c++ versions of c headers. Passes both cosim and on f1. 
Addresses #202

### CODE REVIEW

**Comment by max-ruttenberg** [comment]
@save-buffer 

Have you:
1. Run the regression tests this on F1? Compiles?
2. Run the regression tests this on COSIM? Compiles?

If you have, can you post the output? 

The only reason I can think of that it wouldn't compile might be the need for a `std::` prefix, but I can't remember if that's actually needed. I would think that it isn't but it's good practice to run the regression tests anyway.

**Comment by save-buffer** [comment]
On F1:
image
image

All the tests pass in cosim as well, but after they've all run I'm getting some error about not finding `cadenv.mk`.

**Comment by max-ruttenberg** [comment]
@drichmond have you seen that error before?

**Comment by drichmond** [comment]
Negative

**Comment by max-ruttenberg** [comment]
@save-buffer can you get please email me and @drichmond the full log?

Do you see the same error with just dev checked out (without your changes)?

**Comment by max-ruttenberg** [comment]
@save-buffer it sounds to me like you’re missing a repo that should be in the same directory as bsg_f1.

**Comment by save-buffer** [comment]
Ah, sorry, I didn't see these comments for some reason in my email. I don't have `bsg_cadenv` cloned.

**Pull request merged**
