### PR TITLE
Fix the returning data to endpoint

### PR DESCRIPTION
**Pull request by leonardxiang**
Fix the returning data to the manycore.

library and spmd simulation test passed.

basejump_stl: b0374c2
bsg_manycore: 75219ce

### CODE REVIEW

**Comment by drichmond** [comment]
Hi Leonard, 

Is this a bug you solved? I don't understand what this PR addresses

**Comment by leonardxiang** [comment]
> Hi Leonard,
> 
> Is this a bug you solved? I don't understand what this PR addresses

Hi, Dustin,
This is a bug if the host is working as a slave and response to the manycore request. 
Although currently we don't have this situation in bladerunner, it is good to be fixed.

**Comment by drichmond** [comment]
Cool, good catch. Can you file an issue so that we can track this bug? 

Even if it’s a simple description, reference the line of code so that we can track this in the future.

**Comment by drichmond** [comment]
Addresses #299

**Comment by leonardxiang** [comment]
Address issue #299

**Pull request merged**
