### PR TITLE
Update/remove deprecated library regression tests

### PR DESCRIPTION
**Pull request by bornaehsani**
The following library regression tests have already been replaced with new version in the new refactored API, and therefore should be deleted:
1. test_dmem_read_write --> test_manycore_dmem_read_write
2. test_dram_read_write --> test_manycore_dram_read_write
3. test_packets --> test_manycore_packets

The following tests have been updated based on the refactored API: 
1. test_vcache_sequence

### CODE REVIEW

**Comment by drichmond** [comment]
Should be rebased when #257 is accepted. But otherwise, looks good!

**Comment by max-ruttenberg** [comment]
Tested on F1? COSIM?

**Comment by drichmond** [comment]
Passes in Cosim?

**Comment by drichmond** [comment]
Can you squash commits like "minor fix" or replace them with more descriptive commit messages?

**Comment by bornaehsani** [comment]
F1 and COSIM passed. I also squashed the minor fix commit messages, thanks for reminding me. We are good to go.

**Pull request merged**
