### PR TITLE
Refactored get_config to read configurations from table

### PR DESCRIPTION
**Pull request by save-buffer**
Addresses #173

### CODE REVIEW

**Comment by max-ruttenberg** [comment]
Is this PR stale?

**Comment by save-buffer** [comment]
I'm not quite sure what the status on whether we need this feature or not is. It definitely needs rebasing.

**Comment by max-ruttenberg** [comment]
What is exactly is the feature?

**Comment by save-buffer** [comment]
To read the ROM from a device when it is initialized, and store the contents in a table indexed by that device's file descriptor. This change is necessary because we just refactored `hb_mc_format_request_packet` to have a call to `get_config`. This call will be very very slow under heavy network load if we don't do this because it will have to go to the rom each time a packet has to be formatted.

**Comment by save-buffer** [comment]
But @drichmond said that we were still deciding whether to include it like this or as part of a much larger refactor.

**Comment by drichmond** [comment]
Yes - Sasha is correct here. I asked him to do this to solve this problem, but our intended refactor that we finalized this morning will make this PR stale.

**Pull request closed without merging**
